CREATE TABLE IF NOT EXISTS produtos {
    id SERIAL PRIMARY KEY,
    descrição VARCHAR(255) NOT NULL,
    preço NUMERIC NOT NULL,
    quantidade INTEGER NOT NULL,
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP    
}